[programs.localnet]
renext_program = "HVkuaP3hB997UupdQ9Wc9McurAYBPMDAkw5WS8EahgZw"

[programs.mainnet]
renext_program = "CSUHMpN2gikudkdcJ3rNcbaXUiUi5LSmKc6YsNviUSpx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
